import { Component, OnDestroy, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NavigationEnd, Router, RouterOutlet } from '@angular/router';
import { filter, Subscription } from 'rxjs';
import { ApiService } from './core/api.service';
import { AccessGroup, Assessment, ClinicalRecord, Evolution, Patient, Permission, User } from './core/models';

type Page = 'dashboard' | 'patients' | 'records' | 'new-record' | 'users' | 'groups';
const pagePaths: Record<Page, string> = { dashboard: '/', patients: '/patients', records: '/records', 'new-record': '/new-record', users: '/user', groups: '/groups' };
@Component({ selector: 'app-root', imports: [CommonModule, FormsModule, RouterOutlet], templateUrl: './app.html', styleUrl: './app.scss' })
export class App implements OnInit, OnDestroy {
  readonly user = signal<User | null>(null); readonly page = signal<Page>('dashboard'); readonly patients = signal<Patient[]>([]); readonly records = signal<ClinicalRecord[]>([]); readonly assessments = signal<Assessment[]>([]); readonly evolutions = signal<Evolution[]>([]); readonly users = signal<User[]>([]); readonly groups = signal<AccessGroup[]>([]); readonly permissions = signal<Permission[]>([]); readonly dashboard = signal({ active_patients: 0, initial_assessments: 0, records_this_month: 0 }); readonly loading = signal(false); readonly error = signal(''); readonly toast = signal(''); readonly searchResults = signal<Patient[]>([]); readonly patientPhotos = signal<Record<number, string>>({}); readonly userPhotos = signal<Record<number, string>>({}); readonly patientPreview = signal(''); readonly userPreview = signal(''); readonly dark = signal(false); readonly modal = signal<'patient' | 'user' | 'search' | 'record' | null>(null); readonly editingUser = signal<User | null>(null); readonly editingGroup = signal<AccessGroup | null>(null); readonly selectedRecord = signal<Assessment | Evolution | null>(null); readonly selectedRecordType = signal<'initial_assessment' | 'evolution'>('initial_assessment'); readonly recordStep = signal<1 | 2 | 3 | 4>(1); readonly recording = signal(false); readonly audioReady = signal(false); recordSearch = ''; recordTypeFilter = 'all'; recordSeconds = 0; private recordTimer?: number; private mediaRecorder?: MediaRecorder; private mediaStream?: MediaStream; searchQuery = ''; private readonly routerSubscription: Subscription;
  login = { email: 'andre@fisio1.com.br', password: 'andre' }; patientForm: Partial<Patient> = this.emptyPatient(); recordForm = { patient_id: 0, type: 'initial_assessment', performed_at: new Date().toISOString().slice(0, 10), indication: '', birthplace: '', marital_status: '', gender: '', profession: '', address: '', chief_complaint: '', condition_history: '', life_habits: '', personal_family_history: '', previous_treatments: '', physical_examination: '', complementary_exams: '', physical_therapy_diagnosis: '', cbdf: '', planned_sessions: null as number | null, resources_methods_techniques: '', therapeutic_objectives: '', physical_therapy_prognosis: '', daily_complaint: '', pain_level: null as number | null, home_guidance_adherence: '', therapeutic_conduct: '', session_final_impression: '', observations: '' }; userForm = { name: '', email: '', password: '', access_group_ids: [] as number[] }; groupForm = { name: '', description: '', permission_ids: [] as number[] }; files: File[] = []; audioFile: File | null = null; patientPhoto: File | null = null; userPhoto: File | null = null; editingPatient: Patient | null = null; private audioChunks: Blob[] = []; private navigating = false;
  constructor(private readonly api: ApiService, private readonly router: Router) { this.routerSubscription = this.router.events.pipe(filter(event => event instanceof NavigationEnd)).subscribe(() => { if (this.user() && !this.navigating) void this.load(this.pageFromUrl(), true); }); }
  async ngOnInit() { this.setTheme(localStorage.getItem('fisio1-theme') === 'dark'); if (sessionStorage.getItem('fisio1-token')) try { this.user.set((await this.api.me()).data); await this.load(this.pageFromUrl(), false); } catch { this.logout(); } }
  ngOnDestroy() { this.routerSubscription.unsubscribe(); }
  can(permission: string) { return this.user()?.permissions?.includes(permission) ?? false; }
  async signIn() { await this.run(async () => { const response = await this.api.login(this.login.email, this.login.password); sessionStorage.setItem('fisio1-token', response.data.token); this.user.set(response.data.user); await this.load('dashboard'); }); }
  async requestReset() { await this.run(async () => { const response = await this.api.forgotPassword(this.login.email); this.notice(response.message); }); }
  logout() { sessionStorage.removeItem('fisio1-token'); this.user.set(null); this.page.set('dashboard'); }
  async load(page: Page, fromRoute = false) { if (!fromRoute) { this.navigating = true; await this.router.navigateByUrl(pagePaths[page]); this.navigating = false; } this.page.set(page); await this.run(async () => { if (page === 'dashboard') { const dashboard = (await this.api.dashboard()).data; this.dashboard.set(dashboard); this.records.set(dashboard.recent_records); } if (page === 'patients' || page === 'new-record') this.patients.set((await this.api.patients()).data); if (page === 'records') { this.assessments.set((await this.api.assessments()).data); this.evolutions.set((await this.api.evolutions()).data); } if (page === 'users') { this.users.set((await this.api.users()).data); this.groups.set((await this.api.groups()).data); } if (page === 'groups') { this.groups.set((await this.api.groups()).data); this.permissions.set((await this.api.permissions()).data); } }); }
  async savePatient() { await this.run(async () => { if (this.editingPatient) await this.api.updatePatient(this.editingPatient.id, this.patientForm, this.patientPhoto); else await this.api.createPatient(this.patientForm, this.patientPhoto); this.notice('Paciente salvo com sucesso.'); this.closeModal(); await this.load('patients'); }); }
  editPatient(patient: Patient) { this.editingPatient = patient; this.patientPhoto = null; this.patientPreview.set(''); this.patientForm = { ...patient }; this.modal.set('patient'); }
  openPatientModal() { this.editingPatient = null; this.patientForm = this.emptyPatient(); this.patientPhoto = null; this.patientPreview.set(''); this.modal.set('patient'); }
  closeModal() { this.modal.set(null); this.editingPatient = null; this.editingUser.set(null); this.patientPhoto = null; this.userPhoto = null; this.patientPreview.set(''); this.userPreview.set(''); }
  onPatientPhoto(event: Event) { const photo = (event.target as HTMLInputElement).files?.[0] ?? null; this.patientPhoto = photo; this.patientPreview.set(photo ? URL.createObjectURL(photo) : ''); }
  openNewRecord(patientId = 0) { this.recordStep.set(1); this.recording.set(false); this.audioReady.set(false); this.recordSeconds = 0; this.audioFile = null; this.recordForm = { ...this.recordForm, patient_id: patientId, type: 'initial_assessment', performed_at: new Date().toISOString().slice(0, 10) }; void this.load('new-record'); }
  continueToAudio() { if (!this.recordForm.patient_id) { this.error.set('Selecione um paciente para continuar.'); return; } this.recordStep.set(2); }
  async toggleRecording() { if (this.mediaRecorder?.state === 'recording') { this.mediaRecorder.stop(); return; } try { this.mediaStream = await navigator.mediaDevices.getUserMedia({ audio: true }); this.mediaRecorder = new MediaRecorder(this.mediaStream); this.audioChunks = []; this.mediaRecorder.ondataavailable = event => { if (event.data.size) this.audioChunks.push(event.data); }; this.mediaRecorder.onstop = () => { const blob = new Blob(this.audioChunks, { type: this.mediaRecorder?.mimeType || 'audio/webm' }); this.audioFile = new File([blob], `atendimento-${Date.now()}.webm`, { type: blob.type }); this.mediaStream?.getTracks().forEach(track => track.stop()); this.mediaStream = undefined; this.recording.set(false); window.clearInterval(this.recordTimer); this.audioReady.set(true); this.notice('Gravação concluída e pronta para processar.'); }; this.mediaRecorder.start(); this.recordSeconds = 0; this.recording.set(true); this.recordTimer = window.setInterval(() => this.recordSeconds += 1, 1000); } catch { this.error.set('Não foi possível acessar o microfone. Envie um arquivo de áudio para continuar.'); } }
  audioTime() { return `${String(Math.floor(this.recordSeconds / 60)).padStart(2, '0')}:${String(this.recordSeconds % 60).padStart(2, '0')}`; }
  onAudio(event: Event) { const audio = (event.target as HTMLInputElement).files?.[0] ?? null; if (audio) { this.audioFile = audio; this.recording.set(false); window.clearInterval(this.recordTimer); this.audioReady.set(true); this.notice('Áudio carregado e pronto para processar.'); } }
  async processAudio() { if (!this.audioFile) { this.error.set('Grave ou envie um arquivo de áudio para processar.'); return; } this.recording.set(false); window.clearInterval(this.recordTimer); this.recordStep.set(3); await this.run(async () => { const form = new FormData(); form.append('patient_id', String(this.recordForm.patient_id)); form.append('type', this.recordForm.type); form.append('performed_at', this.recordForm.performed_at); form.append('audio', this.audioFile!); const draft = (await this.api.processClinicalAudio(form)).data; this.recordForm = { ...this.recordForm, ...draft.fields } as typeof this.recordForm; this.recordStep.set(4); this.notice('Áudio transcrito e campos preenchidos para sua revisão.'); }); }
  private applyMockClinicalFields() { const evolution = this.recordForm.type === 'evolution'; this.recordForm = evolution ? { ...this.recordForm, pain_level: 3, daily_complaint: 'Paciente relata melhora importante da dor e maior facilidade nas atividades diárias.', home_guidance_adherence: 'Realizou os exercícios orientados em casa, sem intercorrências.', therapeutic_conduct: 'Progressão dos exercícios de fortalecimento, equilíbrio e treino funcional.', session_final_impression: 'Paciente tolerou bem a sessão.', observations: 'Sem intercorrências durante o atendimento.' } : { ...this.recordForm, indication: 'Dor lombar', chief_complaint: 'Dor lombar há aproximadamente três semanas, principalmente ao permanecer sentado.', condition_history: 'Início após aumento da carga de treino. Nega trauma ou cirurgia recente.', life_habits: 'Pratica atividade física regularmente.', personal_family_history: 'Sem antecedentes relevantes relatados.', previous_treatments: 'Não realizou tratamento fisioterapêutico anterior.', physical_examination: 'Mobilidade lombar reduzida, tensão de cadeia posterior e déficit de estabilização.', physical_therapy_diagnosis: 'Disfunção musculoesquelética lombar.', cbdf: 'Classificação a confirmar pelo profissional.', planned_sessions: 10, resources_methods_techniques: 'Exercícios de mobilidade e estabilização lombopélvica.', therapeutic_objectives: 'Reduzir a dor e retornar gradualmente aos treinos.', physical_therapy_prognosis: 'Favorável mediante adesão ao plano terapêutico.' }; }
  async saveRecord() { await this.run(async () => { if (this.recordForm.type === 'evolution') await this.api.createEvolution({ patient_id: this.recordForm.patient_id, evolved_at: this.recordForm.performed_at, daily_complaint: this.recordForm.daily_complaint, pain_level: this.recordForm.pain_level, home_guidance_adherence: this.recordForm.home_guidance_adherence, therapeutic_conduct: this.recordForm.therapeutic_conduct, session_final_impression: this.recordForm.session_final_impression, observations: this.recordForm.observations }, this.files); else await this.api.createAssessment({ patient_id: this.recordForm.patient_id, assessed_at: this.recordForm.performed_at, indication: this.recordForm.indication, birthplace: this.recordForm.birthplace, marital_status: this.recordForm.marital_status, gender: this.recordForm.gender, profession: this.recordForm.profession, address: this.recordForm.address, chief_complaint: this.recordForm.chief_complaint, condition_history: this.recordForm.condition_history, life_habits: this.recordForm.life_habits, personal_family_history: this.recordForm.personal_family_history, previous_treatments: this.recordForm.previous_treatments, physical_examination: this.recordForm.physical_examination, complementary_exams: this.recordForm.complementary_exams, physical_therapy_diagnosis: this.recordForm.physical_therapy_diagnosis, cbdf: this.recordForm.cbdf, planned_sessions: this.recordForm.planned_sessions, resources_methods_techniques: this.recordForm.resources_methods_techniques, therapeutic_objectives: this.recordForm.therapeutic_objectives, physical_therapy_prognosis: this.recordForm.physical_therapy_prognosis }, this.files); this.files = []; this.notice('Registro revisado e salvo no histórico.'); await this.load('records'); }); }
  onFiles(event: Event) { this.files = Array.from((event.target as HTMLInputElement).files ?? []); }
  async openRecord(type: 'initial_assessment' | 'evolution', id: number) { await this.run(async () => { const record = type === 'evolution' ? (await this.api.evolution(id)).data : (await this.api.assessment(id)).data; this.selectedRecord.set(record); this.selectedRecordType.set(type); this.modal.set('record'); }); }
  async addRecordAttachments(event: Event) { const files = Array.from((event.target as HTMLInputElement).files ?? []); const record = this.selectedRecord(); if (!record || !files.length) return; await this.run(async () => { const updated = this.selectedRecordType() === 'evolution' ? (await this.api.addEvolutionAttachments(record.id, files)).data : (await this.api.addAssessmentAttachments(record.id, files)).data; this.selectedRecord.set(updated); this.notice('Anexo(s) adicionado(s).'); }); }
  async deleteRecordAttachment(id: number) { await this.run(async () => { await this.api.deleteAttachment(id); const record = this.selectedRecord(); if (record) this.selectedRecord.set({ ...record, attachments: record.attachments.filter(attachment => attachment.id !== id) }); this.notice('Anexo removido.'); }); }
  async downloadRecordAttachment(id: number, name: string) { await this.run(async () => { const url = URL.createObjectURL(await this.api.attachment(id)); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }); }
  selectedRecordDate() { const record = this.selectedRecord(); return record ? (this.selectedRecordType() === 'evolution' ? (record as Evolution).evolved_at : (record as Assessment).assessed_at) : ''; }
  recordDetailFields() { const record = this.selectedRecord(); if (!record) return []; if (this.selectedRecordType() === 'evolution') { const item = record as Evolution; return [['Queixa do dia', item.daily_complaint], ['Nível de dor', item.pain_level === null ? null : `${item.pain_level}/10`], ['Adesão às orientações domiciliares', item.home_guidance_adherence], ['Conduta terapêutica', item.therapeutic_conduct], ['Impressão final da sessão', item.session_final_impression], ['Observações', item.observations]]; } const item = record as Assessment; return [['Indicação', item.indication], ['Queixa principal', item.chief_complaint], ['História da doença', item.condition_history], ['Hábitos de vida', item.life_habits], ['Antecedentes pessoais e familiares', item.personal_family_history], ['Tratamentos realizados', item.previous_treatments], ['Exame físico', item.physical_examination], ['Exames complementares', item.complementary_exams], ['Diagnóstico fisioterapêutico', item.physical_therapy_diagnosis], ['CBDF', item.cbdf], ['Recursos, métodos e técnicas', item.resources_methods_techniques], ['Objetivos terapêuticos', item.therapeutic_objectives], ['Prognóstico', item.physical_therapy_prognosis]].filter(([, value]) => value); }
  filteredRecords() { const items = [...this.assessments().map(item => ({ id: item.id, patient: item.patient, professional: item.professional, type: 'initial_assessment' as const, performed_at: item.assessed_at, pain_level: null })), ...this.evolutions().map(item => ({ id: item.id, patient: item.patient, professional: item.professional, type: 'evolution' as const, performed_at: item.evolved_at, pain_level: item.pain_level }))]; const term = this.recordSearch.trim().toLowerCase(); return items.filter(record => (this.recordTypeFilter === 'all' || record.type === this.recordTypeFilter) && (!term || record.patient.name.toLowerCase().includes(term))).sort((a, b) => b.performed_at.localeCompare(a.performed_at)); }
  openUserModal(user?: User) { this.editingUser.set(user ?? null); this.userPhoto = null; this.userPreview.set(''); this.userForm = user ? { name: user.name, email: user.email, password: '', access_group_ids: user.access_groups.map(group => group.id) } : { name: '', email: '', password: '', access_group_ids: [] }; this.modal.set('user'); }
  async saveUser() { await this.run(async () => { const payload = { ...this.userForm, ...(this.userForm.password ? {} : { password: undefined }) }; if (this.editingUser()) await this.api.updateUser(this.editingUser()!.id, payload, this.userPhoto); else await this.api.createUser(this.userForm, this.userPhoto); this.notice(this.editingUser() ? 'Usuário atualizado.' : 'Usuário criado.'); this.closeModal(); await this.load('users'); }); }
  async toggleUser(user: User) { await this.run(async () => { await this.api.updateUser(user.id, { is_active: !user.is_active }); await this.load('users'); }); }
  editGroup(group: AccessGroup) { this.editingGroup.set(group); this.groupForm = { name: group.name, description: group.description ?? '', permission_ids: group.permissions.map(permission => permission.id) }; }
  cancelGroupEdit() { this.editingGroup.set(null); this.groupForm = { name: '', description: '', permission_ids: [] }; }
  async saveGroup() { await this.run(async () => { if (this.editingGroup()) await this.api.updateGroup(this.editingGroup()!.id, this.groupForm); else await this.api.createGroup(this.groupForm); this.notice(this.editingGroup() ? 'Grupo atualizado.' : 'Grupo criado.'); this.cancelGroupEdit(); await this.load('groups'); }); }
  openSearchModal() { this.searchQuery = ''; this.searchResults.set([]); this.modal.set('search'); }
  async searchPatients(query: string) { this.searchQuery = query; if (query.trim().length < 2) { this.searchResults.set([]); return; } try { this.searchResults.set((await this.api.patients(query)).data); } catch { this.searchResults.set([]); } }
  async openPatient(patient: Patient) { this.searchResults.set([]); this.modal.set(null); await this.router.navigateByUrl('/patients'); this.patients.set([patient]); this.notice(`Paciente selecionado: ${patient.name}`); }
  toggleTheme() { this.setTheme(!this.dark()); }
  async downloadPdf(patient: Patient) { await this.run(async () => { const url = URL.createObjectURL(await this.api.pdf(patient.id)); const link = document.createElement('a'); link.href = url; link.download = `historico-${patient.id}.pdf`; link.click(); URL.revokeObjectURL(url); }); }
  groupNames(groups: { name: string }[]) { return groups.map(group => group.name).join(', '); }
  firstName(name?: string) { return name?.split(' ')[0] ?? ''; }
  photoUrl(patient: Patient) { const cached = this.patientPhotos()[patient.id]; if (!cached && patient.has_photo) void this.loadPatientPhoto(patient); return cached ?? ''; }
  onUserPhoto(event: Event) { const photo = (event.target as HTMLInputElement).files?.[0] ?? null; this.userPhoto = photo; this.userPreview.set(photo ? URL.createObjectURL(photo) : ''); }
  patientModalPhoto() { return this.patientPreview() || (this.editingPatient ? this.photoUrl(this.editingPatient) : ''); }
  userModalPhoto() { const user = this.editingUser(); return this.userPreview() || (user ? this.userPhotoUrl(user) : ''); }
  userPhotoUrl(user: User) { const cached = this.userPhotos()[user.id]; if (!cached && user.has_photo) void this.loadUserPhoto(user); return cached ?? ''; }
  togglePermission(id: number) { const index = this.groupForm.permission_ids.indexOf(id); if (index >= 0) this.groupForm.permission_ids.splice(index, 1); else this.groupForm.permission_ids.push(id); }
  private emptyPatient(): Partial<Patient> { return { name: '', document: '', birth_date: '', phone: '', email: '', notes: '' }; }
  private async run(task: () => Promise<void>) { const startedAt = performance.now(); this.loading.set(true); this.error.set(''); try { await task(); } catch (error: unknown) { this.error.set(error instanceof Error ? error.message : 'Não foi possível concluir a ação.'); } finally { const remaining = 350 - (performance.now() - startedAt); if (remaining > 0) await new Promise<void>(resolve => window.setTimeout(resolve, remaining)); this.loading.set(false); } }
  private notice(message: string) { this.toast.set(message); setTimeout(() => this.toast.set(''), 3500); }
  private setTheme(dark: boolean) { this.dark.set(dark); document.documentElement.dataset['theme'] = dark ? 'dark' : 'light'; localStorage.setItem('fisio1-theme', dark ? 'dark' : 'light'); }
  private async loadPatientPhoto(patient: Patient) { try { const src = URL.createObjectURL(await this.api.photo(patient.id)); this.patientPhotos.update(photos => ({ ...photos, [patient.id]: src })); } catch { /* keep initials when the photo cannot be loaded */ } }
  private async loadUserPhoto(user: User) { try { const src = URL.createObjectURL(await this.api.userPhoto(user.id)); this.userPhotos.update(photos => ({ ...photos, [user.id]: src })); } catch { /* keep initials when the photo cannot be loaded */ } }
  private pageFromUrl(): Page { return ({ '/patients': 'patients', '/records': 'records', '/new-record': 'new-record', '/user': 'users', '/groups': 'groups' } as Record<string, Page>)[this.router.url.split('?')[0]] ?? 'dashboard'; }
}
